### ISSUE TITLE
Github discord bot posts to #development

### ISSUE THREAD

**Issue by jasbrake** [ActionFPS/blacklist#2]
Blacklisting is more of an administration task than a development one (despite using Github). I think if the Github bot posted all updates for the project to the #tribunal channel it could be cleaner and more efficient.

Thoughts?

**Comment by ScalaWilliam** [comment]
That's 2 separate problems, really:
1. Posting to dev channel
2. Posting to tribunal channel

I can configure a new link to the second channel, there's too many requests for it :P

**Comment by ScalaWilliam** [comment]
Test

**Comment by ScalaWilliam** [comment]
Test

**Comment by ScalaWilliam** [comment]
Done:
![screen shot 2017-04-16 at 20 21 08](https://cloud.githubusercontent.com/assets/2464813/25071128/40639f24-22e2-11e7-82de-bcf3c1d74d32.png)
